services:
  backend:
    build:
      context: .
    image: backend:1.0.0
    command: [ "sh", "-c", "sleep 5 && .venv/bin/alembic upgrade head && .venv/bin/uvicorn src.main:app --host 0.0.0.0 --port 8000" ]
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - "./logs:/app/logs"
    networks:
      - main-network
    restart: always
    depends_on:
      - database
      - redis
    
  database:
    image: postgres:14-alpine
    container_name: database
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ".env"
    networks:
      - main-network
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - ".env"
    restart: always
    networks:
      - main-network
    depends_on:
      - database

  redis:
    container_name: redis
    image: redis:7.4
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--maxmemory", "0", "--maxmemory-policy", "noeviction", "--save", "3600 1 300 100 60 10000", "--maxclients", "1000" ]
    volumes:
      - redis-data:/root/redis
    env_file:
      - ".env"
    networks:
      - main-network
    restart: always

networks:
  main-network:
    driver: bridge

volumes:
  db-data:
  redis-data:
